# Form implementation generated from reading ui file 'password.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import  QMessageBox
import random
import secrets
import pyperclip


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(586, 415)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 30, 511, 131))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 230, 87, 79))
        self.label_2.setObjectName("label_2")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(40, 280, 501, 81))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton.setObjectName("pushButton")

        self.pushButton.clicked.connect(self.password_generate)

        self.horizontalLayout.addWidget(self.pushButton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 586, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def password_generate(self):
        symbols = list('!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~')
        nums = list('0123456789')
        capital_letters = list('ABCDEFGHIJKLMNOPQRSTUVWXYZ')
        letters = list('abcdefghijklmnopqrstuvwxyz')
        all_character = symbols + nums + capital_letters + letters

        password_length = int(self.lineEdit.text())  # Get the length of the password
        password_minus_four = password_length - 4  # Makes sure we add from all lists

        psw1 = ''.join(secrets.choice(symbols) for _ in range(1))
        psw2 = ''.join(secrets.choice(nums) for _ in range(1))
        psw3 = ''.join(secrets.choice(capital_letters) for _ in range(1))
        psw4= ''.join(secrets.choice(letters) for _ in range(1))

        password = ([psw1, psw2, psw3, psw4] +
                       [secrets.choice(all_character) for _ in range(password_minus_four)])


        psw_shuffle = ''.join(random.sample(password, len(password)))


        # Copy to clipboard
        pyperclip.copy(psw_shuffle)

        self.label.setText(psw_shuffle)

        QMessageBox.information(None,"Information", "Password copied to clipboard")


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Password generator"))
        self.label.setText(_translate("MainWindow", ""))
        self.label_2.setText(_translate("MainWindow", "Password length"))
        self.lineEdit.setText(_translate("MainWindow", "15"))
        self.pushButton.setText(_translate("MainWindow", "Generate"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
